from abc import ABCMeta
import fnmatch
from typing import Any, Callable, Mapping, Optional, Tuple, TypeVar, Union

T = TypeVar('T')
# EQ_TYPE = Union[NotImplemented, bool]

class _NamedTupleMeta(ABCMeta):
    def __new__(mcs: Any, name: Any, bases: Any, namespace: Any): ...

class BaseMetadata(metaclass=_NamedTupleMeta):
    DEFAULT_NAME: str = ...
    def __eq__(self , other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def combine(self: T, other: T, lenient: Optional[bool] = ...) -> T: ...
    def difference(self: T, other: T, lenient: Optional[bool] = ...) -> Optional[T]: ...
    def equal(self: T, other: T, lenient: Optional[Any] = ...) -> bool: ...
    @classmethod
    def from_metadata(cls: T, other: BaseMetadata) -> T: ...
    def name(self, default: Optional[str] = ..., token: bool = ...) -> str: ...
    @classmethod
    def token(cls, name: str) -> Optional[str]: ...

class AncillaryVariableMetadata(BaseMetadata):
    def __eq__(self, other: object) -> bool: ...
    def combine(self: T, other: T, lenient: Optional[bool] = ...) -> T: ...
    def difference(self: T, other: T, lenient: Optional[bool] = ...) -> Optional[T]: ...
    def equal(self: T, other: T, lenient: Optional[Any] = ...) -> bool: ...

class CellMeasureMetadata(BaseMetadata):
    def __eq__(self, other: object) -> bool: ...
    def combine(self: T, other: T, lenient: Optional[bool] = ...) -> T: ...
    def difference(self: T, other: T, lenient: Optional[bool] = ...) -> Optional[T]: ...
    def equal(self: T, other: T, lenient: Optional[Any] = ...) -> bool: ...

class CoordMetadata(BaseMetadata):
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def combine(self: T, other: T, lenient: Optional[bool] = ...) -> T: ...
    def difference(self: T, other: T, lenient: Optional[bool] = ...) -> Optional[T]: ...
    def equal(self: T, other: T, lenient: Optional[Any] = ...) -> bool: ...

class CubeMetadata(BaseMetadata):
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def combine(self: T, other: T, lenient: Optional[bool] = ...) -> T: ...
    def difference(self: T, other: T, lenient: Optional[bool] = ...) -> Optional[T]: ...
    def equal(self: T, other: T, lenient: Optional[Any] = ...) -> bool: ...
    attributes: Mapping[str, Any] = ...
    def name(self, default: Optional[str] = ..., token: bool = ...) -> str: ...

class DimCoordMetadata(CoordMetadata):
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def combine(self: T, other: T, lenient: Optional[bool] = ...) -> T: ...
    def difference(self: T, other: T, lenient: Optional[bool] = ...) -> Optional[T]: ...
    def equal(self: T, other: T, lenient: Optional[Any] = ...) -> bool: ...

def metadata_manager_factory(cls: BaseMetadata, **kwargs: Any): ...

fn = Tuple[BaseMetadata, Callable[[T, T, Optional[bool]], T]]

SERVICES_COMBINE: fn
SERVICES_DIFFERENCE: fn
SERVICES_EQUAL: fn
SERVICES: fn
